import { betterAuth, type BetterAuthOptions } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { username } from "better-auth/plugins";
import * as dotenv from "dotenv";

// Load environment variables from multiple possible locations
// This ensures DATABASE_URL is available when importing the db package
const envPaths = [".env", "../.env", "../../.env", "../../apps/server/.env"];

for (const envPath of envPaths) {
  try {
    dotenv.config({ path: envPath });
    if (process.env.DATABASE_URL) break;
  } catch {
    // Continue to next path
  }
}

// Import db after loading environment variables
import { db, schema } from "@benkyou/db";

// Get both the Next.js origin (for proxy) and the direct server origin
const nextJsOrigin = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3001";
const serverOrigin = process.env.CORS_ORIGIN || "http://localhost:3001";

export const auth = betterAuth<BetterAuthOptions>({
  database: drizzleAdapter(db, {
    provider: "pg", // PostgreSQL provider for Supabase
    schema, // Pass the schema generated by Better Auth CLI
  }),
  // Trust both Next.js origin (for proxy requests) and direct server origin
  trustedOrigins: [nextJsOrigin, serverOrigin].filter(Boolean),
  emailAndPassword: {
    enabled: true,
  },
  plugins: [
    username(), // Add username plugin
  ],
  advanced: {
    defaultCookieAttributes: {
      // For proxy setup, use 'lax' in development, 'none' in production with HTTPS
      sameSite: process.env.NODE_ENV === "production" ? "none" : "lax",
      secure: process.env.NODE_ENV === "production",
      httpOnly: true,
    },
  },
});
