import { betterAuth, type BetterAuthOptions } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { username } from "better-auth/plugins";
import * as dotenv from "dotenv";

// Load environment variables from multiple possible locations
// This ensures DATABASE_URL is available when importing the db package
const envPaths = [".env", "../.env", "../../.env", "../../apps/server/.env"];

for (const envPath of envPaths) {
  try {
    dotenv.config({ path: envPath });
    if (process.env.DATABASE_URL) break;
  } catch {
    // Continue to next path
  }
}

// Import db after loading environment variables
import { db, schema } from "@benkyou/db";

export const auth = betterAuth<BetterAuthOptions>({
  database: drizzleAdapter(db, {
    provider: "pg", // PostgreSQL provider for Supabase
    schema, // Pass the schema generated by Better Auth CLI
  }),
  trustedOrigins: [process.env.CORS_ORIGIN || ""],
  emailAndPassword: {
    enabled: true,
  },
  plugins: [
    username(), // Add username plugin
  ],
  advanced: {
    defaultCookieAttributes: {
      sameSite: "none",
      secure: true,
      httpOnly: true,
    },
  },
});
